name: main
on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths: ['**.css', '**.html', '**.json', '**.jsonc', '**.md', '**.yml']
  push:
    branches: [main]
    paths: ['**.css', '**.html', '**.json', '**.jsonc', '**.md', '**.yml']

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dprint/check@v2.2
